# Generated by Django 5.2.1 on 2025-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=64, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
