# Generated by Django 5.2.1 on 2025-05-14 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_customuser_last_login_class_classschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 14, 12, 8, 39, 831238, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
